//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Command
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Broker
    {
		public virtual List<IOrder> OrderList
        {
			get;
			set;
		}

		public virtual void PlaceOrders()
		{
            foreach (var o in OrderList)
            {
                o.Execute();
            }
		}

		public virtual void TakeOrder(IOrder order)
		{
            OrderList.Add(order);
        }

	}
}

