//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Strategy
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Add : IStrategy
	{
		public virtual int Operation(int num1, int num2)
		{
			throw new System.NotImplementedException();
		}

	}
}

