//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facade
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Rectangle : IShape
	{
		public virtual void Draw()
		{
            Console.WriteLine("Draw Rectangle");
        }

	}
}

