//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbstractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AbsrtactFactory
	{
		public virtual IShape GetShape(string shapeType)
		{
			throw new System.NotImplementedException();
		}

		public virtual IColor GetColor(string colorType)
		{
			throw new System.NotImplementedException();
		}

	}
}

