//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Chain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AbstractLogger
	{

        public virtual AbstractLogger NextLogger
        {
            get;
            set;
        }

        public virtual Level Level
        {
            get;
            set;
        }

        public virtual void LogMessage(Level level, string message)
        {
            if (this.Level <= level)
            {
                Write(message);
            }
            if (NextLogger != null)
            {
                NextLogger.LogMessage(level, message);
            }
		}

		protected abstract void Write(string message);

	}
}

