//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Memento
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CareTaker
	{
		public virtual IEnumerable<Memento> MementoList
		{
			get;
			set;
		}

	}
}

