//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace State
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class StopState : IState
	{
		public virtual Context Context
		{
			get;
			set;
		}

		public virtual void Action()
		{
            Context.IState = this;
            Console.WriteLine("Player is in stop state");
        }
    }
}

