//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Flyweight
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FlyweightDemo
	{
        private static string[] colors = { "Red", "Green", "Blue", "White", "Black" };
        private static Random r = new Random();

        public void Main()
        {
            for (int i = 0; i < 20; i++)
            {
                var color = GetRandomColor();
                var circle = ShapeFactory.GetCircle(color) as Circle;
                circle.Radius = r.Next(100);
                circle.Draw();
            }
        }
        private static string GetRandomColor()
        {
            
            return colors[r.Next(4)];
        }
    }
}

