//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Flyweight
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class ShapeFactory
    {
        public static Dictionary<string, object> CircleDict
        {
            get;
            private set;
        }

        public static IShape GetCircle(string color)
        {
            if (CircleDict == null)
            {
                CircleDict = new Dictionary<string, object>();
            }

            if (!CircleDict.Keys.Contains(color))
            {
                var circle = new Circle() { Color = color };
                CircleDict.Add(color, circle);
                Console.WriteLine("Creating circle of color : " + color);
                circle.Draw();
            }
            return CircleDict[color] as IShape;
        }

    }
}

