//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Prototype
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Circle : Shape
	{
        public Circle()
        {
            _type = "Circle";
        }

        public override string GetType()
        {
            return _type;
        }

		public override int GetId()
        {
            return _id;
        }

		public override void SetId(int Id)
        {
            _id = Id;
        }

		public override Object Clone()
		{
            throw new System.NotImplementedException();
		}

	}
}

