//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Prototype
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PrototypeDemo
	{
        public void Main()
        {
            var circle = new Prototype.Circle { Id = "circle" };
            var circle1 = circle.Clone() as Prototype.Shape;
            var circle2 = circle.Clone() as Prototype.Shape;
            Console.WriteLine(circle1?.Id);
            Console.WriteLine(circle2?.Id);
        }
    }
}

