//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Prototype
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShapeCache
	{
		private Dictionary<string,string> shapeMap
		{
			get;
			set;
		}

		public virtual Shape GetShape()
		{
			throw new System.NotImplementedException();
		}

		public virtual void LoadCache()
		{
			throw new System.NotImplementedException();
		}

	}
}

