//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Prototype
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Shape
	{
		protected int _id;

		public string _type;

		public abstract string GetType();

		public abstract int GetId();

		public abstract void SetId(int Id);

		public abstract Object Clone();

	}
}

