//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Decorator
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class DecoratorDemo
    {
        public void Main()
        {
            IShape circle = new Circle();
            ShapeDecorator redCircle = new RedShapeDecorator { Shape = new Circle() };
            ShapeDecorator redRectangle = new RedShapeDecorator { Shape = new Rectangle() };

            Console.WriteLine("Circle with normal border");
            circle.Draw();

            Console.WriteLine("Circle of red border");
            redCircle.Draw();

            Console.WriteLine("Rectangle  of red border");
            redRectangle.Draw();
        }
    }
}

