//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Mediator
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class ChatRoom
    {
        public static void ShowMessage(User user, string message)
        {
            Console.WriteLine($"{user.Name}:{message}");
        }

    }
}

