//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Strategy
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class Context
    {
        public virtual IStrategy IStrategy
        {
            get;
            set;
        }

        public virtual int Execute(int num1, int num2)
        {
            return IStrategy.Operation(num1, num2);
        }

    }
}