//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Strategy
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class StrategyDemo
	{
        public void Main()
        {
            Context context = new Context();
            context.IStrategy = new Add();
            Console.WriteLine("10+5:"+context.Execute(10,5));
            context.IStrategy = new Substract();
            Console.WriteLine("10-5:"+context.Execute(10,5));
            context.IStrategy = new Multiply();
            Console.WriteLine("10*5:"+context.Execute(10,5));
        }
    }
}

