//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Adapter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class AdapterDemo
	{
        public void Main()
        {
            AudioPlayer audioPlayer = new AudioPlayer{ MediaAdapter = new MediaAdapter()};

            audioPlayer.Play("mp3", "beyond the horizon.mp3");
            audioPlayer.Play("mp4", "alone.mp4");
            audioPlayer.Play("vlc", "far far away.vlc");
            audioPlayer.Play("avi", "mind me.avi");
        }
	}
}

