//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Adapter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AdvanceMediaPlayer
	{
		public abstract void PlayVlc(string fileName);

		public abstract void PlayMp4(string fileName);

	}
}

