//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Adapter
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class AudioPlayer : IMediaPlayer
    {
        public virtual MediaAdapter MediaAdapter
        {
            get;
            set;
        }

        public virtual void Play(string audioType, string fileName)
        {
            switch (audioType)
            {
                case "mp3":
                    Console.WriteLine("Playing mp3 file. Name: " + fileName);
                    break;
                case "mp4":
                case "vlc":
                    MediaAdapter.Play(audioType, fileName);
                    break;
                default:
                    Console.WriteLine("Invalid media. " + audioType + " format not supported");
                    break;
            }
        }

    }
}

