//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Adapter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MediaAdapter : IMediaPlayer
	{
		public virtual AdvanceMediaPlayer AdvanceMediaPlayer
		{
			private get;
			set;
		}

		public virtual void Play(string audioType, string fileName)
		{
            switch (audioType)
            {
                case "vlc":
                    AdvanceMediaPlayer = new VlcPlayer();
                    AdvanceMediaPlayer.PlayVlc(fileName);
                    break;
                case "mp4":
                    AdvanceMediaPlayer = new Mp4Player();
                    AdvanceMediaPlayer.PlayMp4(fileName);
                    break;
            }

		}

	}
}

