//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Adapter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Mp4Player : AdvanceMediaPlayer
	{
		public override void PlayVlc(string fileName)
		{
			throw new System.NotImplementedException();
		}

		public override void PlayMp4(string fileName)
		{
            Console.WriteLine("Playing mp4 file. Name:" + fileName);
		}

	}
}

