//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Chain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AbstractLogger
	{
		public virtual int level
		{
			get;
			set;
		}

		public virtual int INFO
		{
			get;
			set;
		}

		public virtual int DEBUG
		{
			get;
			set;
		}

		public virtual int ERROR
		{
			get;
			set;
		}

		public virtual AbstractLogger NextLogger
		{
			get;
			set;
		}

		public virtual void SetNextLogger()
		{
			throw new System.NotImplementedException();
		}

		public virtual void LogMessage()
		{
			throw new System.NotImplementedException();
		}

		protected abstract void Write();

	}
}

