//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Chain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ConsoleLogger : AbstractLogger
	{
		protected override void Write(string message)
		{
			throw new System.NotImplementedException();
		}

	}
}

