//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Chain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FileLogger : AbstractLogger
	{
		protected override void Write()
		{
			throw new System.NotImplementedException();
		}

	}
}

