//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Prototype
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Shape
	{
		public virtual string Id
		{
			get;
			set;
		}

		public virtual string Type
		{
			get;
			set;
		}

		public abstract string GetType();

		public abstract string GetId();

		public abstract string SetId();

		public abstract Object Clone();

	}
}

