//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Prototype
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Square : Shape
	{
		public override string GetType()
		{
			throw new System.NotImplementedException();
		}

		public override string GetId()
		{
			throw new System.NotImplementedException();
		}

		public override string SetId()
		{
			throw new System.NotImplementedException();
		}

		public override Object Clone()
		{
			throw new System.NotImplementedException();
		}

	}
}

