//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Command
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BuyStock : IOrder
	{
		public virtual void Execute()
		{
			throw new System.NotImplementedException();
		}

	}
}

