//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Command
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Stock
	{
		public virtual BuyStock BuyStock
		{
			get;
			set;
		}

		public virtual SellStock SellStock
		{
			get;
			set;
		}

		public virtual void Buy()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Sell()
		{
			throw new System.NotImplementedException();
		}

	}
}

