//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facade
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShapeMaker
	{
		public virtual Rectangle Rectangle
		{
			get;
			set;
		}

		public virtual Circle Circle
		{
			get;
			set;
		}

		public virtual void CircleDraw()
		{
			throw new System.NotImplementedException();
		}

		public virtual void RectangleDraw()
		{
			throw new System.NotImplementedException();
		}

	}
}

