//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Facade
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShapeMaker
	{
		public virtual Rectangle Rectangle
		{
			get;
			set;
		}

		public virtual Circle Circle
		{
			get;
			set;
		}

		public virtual void CircleDraw()
		{
			throw new System.NotImplementedException();
		}

		public virtual void RectangleDraw()
		{
			throw new System.NotImplementedException();
		}

	}
}

