//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Memento
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MementoDemo
	{
        public void Main()
        {
            Originator originator = new Originator(){Memento = new Memento()};
            CareTaker careTaker = new CareTaker(){MementoList = new List<Memento>()};

            originator.Memento.State = "State #1";
            originator.Memento.State = "State #2";
            careTaker.MementoList.Add(originator.Memento.Clone() as Memento);
            originator.Memento.State = "State #3";
            careTaker.MementoList.Add(originator.Memento.Clone() as Memento);
            originator.Memento.State = "State #4";
            careTaker.MementoList.Add(originator.Memento.Clone() as Memento);

            Console.WriteLine("Current State:"+originator.Memento.State);
            originator.Memento =careTaker.MementoList[0];
            Console.WriteLine("First State:"+originator.Memento.State);
            originator.Memento =careTaker.MementoList[1];
            Console.WriteLine("Second State:"+originator.Memento.State);
        }
    }
}

