//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Iterator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NameIterator : Iterator
	{
		public virtual bool HasNext()
		{
			throw new System.NotImplementedException();
		}

		public virtual Object Next()
		{
			throw new System.NotImplementedException();
		}

	}
}

