//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Visitor
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class VisitorDemo
    {
        public void Main()
        {
            IComputerPart computer = new Computer();
            IComputerPartVisitor visitor = new ComputerPartVisitor();
            computer.Accept(visitor);
        }
    }
}

