//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Template
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cricket : Game
	{
		public override void Initialize()
		{
			throw new System.NotImplementedException();
		}

		public override void StartPlay()
		{
			throw new System.NotImplementedException();
		}

		public override void EndPlay()
		{
			throw new System.NotImplementedException();
		}

	}
}

