//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Builder
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Burger : Item
	{
		public override IPacking packing(string packingType)
		{
			throw new System.NotImplementedException();
		}

		public override float price()
		{
			throw new System.NotImplementedException();
		}

		public override string GetName()
		{
			throw new System.NotImplementedException();
		}

	}
}

