//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Builder
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Coke : Drink
	{
		public override IPacking Packing()
		{
			throw new System.NotImplementedException();
		}

		public override float GetPrice()
		{
			throw new System.NotImplementedException();
		}

		public override string GetName()
		{
			throw new System.NotImplementedException();
		}

	}
}

