//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Builder
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MealBuilder
	{
		public virtual Meal prepareVegMeal()
		{
			throw new System.NotImplementedException();
		}

		public virtual Meal prepareNonVegMeal()
		{
			throw new System.NotImplementedException();
		}

	}
}

