//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Template
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cricket : Game
	{
        public override void Initialize()
		{
			Console.WriteLine("Cricket Game Initialized! Start playing.");
		}

		public override void StartPlay()
		{
            Console.WriteLine("Cricket Game Started. Enjoy the game!");
		}

		public override void EndPlay()
		{
            Console.WriteLine("Cricket Game Finished!");
		}

	}
}

