//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Template
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TemplateDemo
	{
        public void Main()
        {
            Game game = new Cricket();
            game.Play();
            game = new Football();
            game.Play();
        }

	}
}

