//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Composite
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Employee
	{
		public virtual IEnumerable<Employee> Subordinates
		{
			get;
			set;
		}

		public virtual void Add(Employee e)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Remove(Employee e)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<Employee> GetSubordinates()
		{
			throw new System.NotImplementedException();
		}

	}
}

