//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Observer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BinaryObserver  : Observer
	{
		public override void Update()
		{
			Console.WriteLine("Binary:"+ Convert.ToString(this.Subject.State, 2));
		}

	}
}

