//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Observer
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class ObserverDemo
    {
        public void Main()
        {
            Subject subject = new Subject();
            subject.Observer = new List<Observer>()
            {
                new BinaryObserver(){Subject = subject},
                new HexaObserver(){Subject = subject},
                new OctalObserver(){Subject = subject}
            };
            subject.State = 15;
            subject.Notification();
            subject.State = 10;
            subject.Notification();
        }
    }
}

