//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Observer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Subject
	{
		public virtual int State
		{
			get;
			set;
		}

		public virtual IEnumerable<Observer> Observer
		{
			get;
			set;
		}

		public virtual void Notification()
		{
            foreach (var itemObserver in Observer)
            {
                itemObserver.Update();
            }
		}

	}
}

