//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bridge
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public class BridgeDemo
    {
        public void Main()
        {
            Shape redCircle = new Circle() { Radius = 10, DrawAPI = new RedCircle() };
            Shape greenCircle = new Circle() { Radius = 15, DrawAPI = new GreenCircle() };

            redCircle.Draw();
            greenCircle.Draw();
        }
    }
}

