//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Decorator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class ShapeDecorator : IShape
	{
		public virtual IShape Shape
		{
			get;
			set;
		}

		public virtual void draw()
		{
			throw new System.NotImplementedException();
		}

	}
}

