//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Factory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FactoryDemo
	{
        public void Main()
        {
            var factory = new ShapeFactory();
            var circle = factory.GetSharp(ShapeType.Circle);
            circle.Draw();
            var rectangle = factory.GetSharp(ShapeType.Rectangle);
            rectangle.Draw();
        }
    }
}

