//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Factory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShapeFactory
	{
		public virtual IShape GetSharp(ShapeType shapeType)
        {
            switch (shapeType)
            {
                case ShapeType.Circle:
                    return new Circle();
                case ShapeType.Rectangle:
                    return new Rectangle();
                case ShapeType.Square:
                    return new Square();
            }

            return null;
        }
    }
}

