//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Adapter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MediaAdapter : IMediaPlayer
	{
		public virtual AdvanceMediaPlayer AdvanceMediaPlayer
		{
			get;
			set;
		}

		public virtual void Play()
		{
			throw new System.NotImplementedException();
		}

	}
}

