//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Builder
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BuilderDemo
	{
        public void Main()
        {
            var build = new MealBuilder();
            var meal1 = build.prepareNonVegMeal();
            meal1.GetCost();
            foreach (var iMeal in meal1.Items)
            {
                Console.WriteLine($"Name:{iMeal.GetName()}");
                Console.WriteLine($"Price:{iMeal.GetPrice()}");
                Console.WriteLine($"Pack Way:{iMeal.Packing().Pack()}");
            }
        }
    }
}

