//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Builder
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public abstract class Drink : Item
    {
        public override IPacking Packing()
        {
            return new Bottle();
        }

        public override float GetPrice()
        {
            return (float)1.00;
        }

        public override string GetName()
        {
            return "ChickenBurger";
        }

    }
}

