//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Iterator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class IteratorDemo
	{
        public void Main()
        {
            NameRepository nameRepository = new NameRepository { NameList = new List<string> { "Robert", "John", "Julie", "Lora" } };

            for (Iterator iter = nameRepository.GetIterator(); iter.HasNext();)
            {
                String name = (String)iter.Next();
                Console.WriteLine("Name:" + name);
            }
        }
	}
}

