//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Iterator
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NameIterator : Iterator
	{
        int index;
		public virtual NameRepository NameRepository
		{
			get;
			set;
		}

		public virtual bool HasNext()
		{
            return (index < NameRepository.NameList.Count);

		}

		public virtual Object Next()
		{
            if (HasNext())
            {
                return NameRepository.NameList[index++];
            }
            return null;
		}

	}
}

