//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbstractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AbsrtactFactory
	{
        public virtual IShape GetShape(string shapeType)
        {
            switch (shapeType)
            {
                case "rectangle":
                    return new Rectangle();
                case "square":
                    return new Square();
                case "circle":
                    return new Circle();
            }

            return null;
        }

        public virtual IColor GetColor(string colorType)
        {
            switch (colorType)
            {
                case "red":
                    return new Red();
                case "blue":
                    return new Blue();
                case "green":
                    return new Green();
            }

            return null;
        }

	}
}

