//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbstractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class AbstractFactoryDemo
	{
        public void Main()
        {
            var factory = new FactoryProducter();
            var colorFactory = factory.GetFactory("color");

            var red = colorFactory.GetColor("red");
            var blue = colorFactory.GetColor("blue");
            var shapeFactory = factory.GetFactory("shape");
            var circle = shapeFactory.GetShape("circle");
            circle.Draw();
            red.Fill();
            blue.Fill();
        }
	}
}

