//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AbstractFactory
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShapeFactory : AbsrtactFactory
	{
		public override IShape GetShape(string shapeType)
		{
            switch (shapeType)
            {
                case "rectangle":
                    return new Rectangle();
                case "square":
                    return new Square();
                case "circle":
                    return new Circle();
            }

			return null;
		}

		public override IColor GetColor(string colorType)
		{
			throw new System.NotImplementedException();
		}

	}
}

