//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interpreter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TerminalExpression : IExpression
	{
		public virtual string Data
		{
			get;
			set;
		}

		public virtual bool Interpreter()
		{
			throw new System.NotImplementedException();
		}

	}
}

